apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-be
  namespace: apps-prod
  labels:
    app: portal-be
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portal-be
  template:
    metadata:
      labels:
        app: portal-be
        env: prod
    spec:
      containers:
        - name: portal-be
          image: localhost:32000/portal-be:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: portal-be
  namespace: apps-prod
spec:
  selector:
    app: portal-be
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portal-be
  namespace: apps-prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: api.portal.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portal-be
                port:
                  number: 8080
