apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-fe
  namespace: apps-prod
  labels:
    app: portal-fe
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portal-fe
  template:
    metadata:
      labels:
        app: portal-fe
        env: prod
    spec:
      containers:
        - name: portal-fe
          image: localhost:32000/portal-fe:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: portal-fe
  namespace: apps-prod
spec:
  selector:
    app: portal-fe
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portal-fe
  namespace: apps-prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: portal.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portal-fe
                port:
                  number: 80
