---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portal-postgres-pvc
  namespace: platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-postgres
  namespace: platform
  labels:
    app: portal-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal-postgres
  template:
    metadata:
      labels:
        app: portal-postgres
    spec:
      containers:
        - name: portal-postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: portal-postgres-secret
          volumeMounts:
            - name: portal-postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - portal
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - portal
            initialDelaySeconds: 15
            periodSeconds: 30
      volumes:
        - name: portal-postgres-data
          persistentVolumeClaim:
            claimName: portal-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: portal-postgres
  namespace: platform
  labels:
    app: portal-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: portal-postgres
