apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-be
  namespace: apps-staging
  labels:
    app: portal-be
    env: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal-be
  template:
    metadata:
      labels:
        app: portal-be
        env: staging
    spec:
      containers:
        - name: portal-be
          image: localhost:32000/portal-be:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: portal-be
  namespace: apps-staging
spec:
  selector:
    app: portal-be
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
