apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-fe
  namespace: apps-staging
  labels:
    app: portal-fe
    env: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal-fe
  template:
    metadata:
      labels:
        app: portal-fe
        env: staging
    spec:
      containers:
        - name: portal-fe
          image: localhost:32000/portal-fe:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: portal-fe
  namespace: apps-staging
spec:
  selector:
    app: portal-fe
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
